import pandas as pd
subpath_name = ["Acetylated_Peptides", 	"Alanine_and_Aspartate_Metabolism", 	"Aminosugar_Metabolism", 	"Ascorbate_and_Aldarate_Metabolism", 	"Benzoate_Metabolism", 	"Carnitine_Metabolism", 	"Chemical", 	"Corticosteroids", 	"Creatine_Metabolism", 	"Dipeptide", 	"Disaccharides_and_Oligosaccharides", 	"Drug_Topical_Agents", 	"Fatty_Acid_Amino", 	"Fatty_Acid_Dicarboxylate", 	"Fatty_Acid_Dihydroxy", 	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Dicarboxylate)", 	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Medium_Chain)", 	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Monounsaturated)", 	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Short_Chain)", 	"Fatty_Acid_Metabolism_(also_BCAA_Metabolism)", 	"Fatty_Acid_Monohydroxy", 	"Food_Component_Plant", 	"Fructose_Mannose_and_Galactose_Metabolism", 	"Galactosyl_Glycerolipids", 	"Gammaglutamyl_Amino_Acid", 	"Glutamate_Metabolism", 	"Glutathione_Metabolism", 	"Glycerolipid_Metabolism", 	"Glycine_Serine_and_Threonine_Metabolism", 	"Glycolysis_Gluconeogenesis_and_Pyruvate_Metabolism", 	"Guanidino_and_Acetamido_Metabolism", 	"Hemoglobin_and_Porphyrin_Metabolism", 	"Histidine_Metabolism", 	"Inositol_Metabolism", 	"Ketone_Bodies", 	"Lactoyl_Amino_Acid", 	"Leucine_Isoleucine_and_Valine_Metabolism", 	"Lysine_Metabolism", 	"Lysophospholipid", 	"Methionine_Cysteine_SAM_and_Taurine_Metabolism", 	"Mevalonate_Metabolism", 	"Modified_Peptides", 	"Nicotinate_and_Nicotinamide_Metabolism", 	"Oxidative_Phosphorylation", 	"Pantothenate_and_CoA_Metabolism", 	"Partially_Characterized_Molecules", 	"Pentose_Metabolism", 	"Phenylalanine_Metabolism", 	"Phosphatidylcholine_(PC)", 	"Phosphatidylethanolamine_(PE)", 	"Phospholipid_Metabolism", 	"Plasmalogen", 	"Polyamine_Metabolism", 	"Purine_Metabolism_(Hypo)Xanthine_Inosine_containing", 	"Purine_Metabolism_Adenine_containing", 	"Purine_Metabolism_Guanine_containing", 	"Pyrimidine_Metabolism_Cytidine_containing", 	"Pyrimidine_Metabolism_Orotate_containing", 	"Pyrimidine_Metabolism_Thymine_containing", 	"Pyrimidine_Metabolism_Uracil_containing", 	"Secondary_Bile_Acid_Metabolism", 	"Sphingomyelins", 	"Sterol", 	"TCA_Cycle", 	"Tocopherol_Metabolism", 	"Tryptophan_Metabolism", 	"Tyrosine_Metabolism", 	"Urea_cycle_Arginine_and_Proline_Metabolism", 	"Vitamin_A_Metabolism", 	"Vitamin_B6_Metabolism", 	"Xanthine_Metabolism", ]
for subpath in subpath_name:
    l = ["sid"]
    with open ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/Sub-Pathway/Subpathway_Data.txt", 'r') as subpath_data:
        line = subpath_data.readline ()
        for line in subpath_data:
            line_list = line.split ("\t")
            if (str(line_list [0]) == str(subpath)):
                l.append (str (line_list [2]))
    print (l)
    df = pd.read_csv ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/Metabolites/Full_Data_Metabolites.txt", delimiter="\t")
    df_2 = df[l]
    df_2.to_csv ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/Sub-Pathway/Data_Sub_Pathway/" + str (subpath) + ".txt", sep="\t", index=False)
