import pandas as pd
subpath_name = ["Polyamine_Metabolism",	"Plasmalogen",	"Histidine_Metabolism",	"Nicotinate_and_Nicotinamide_Metabolism",	"Xanthine_Metabolism",	"Phosphatidylcholine_(PC)",	"Lysophospholipid",	"Phosphatidylethanolamine_(PE)",	"Chemical",	"Glycolysis_Gluconeogenesis_and_Pyruvate_Metabolism",	"Glutathione_Metabolism",	"Fatty_Acid_Amino",	"Food_Component_Plant",	"Leucine_Isoleucine_and_Valine_Metabolism",	"Methionine_Cysteine_SAM_and_Taurine_Metabolism",	"Fatty_Acid_Dicarboxylate",	"TCA_Cycle",	"Ascorbate_and_Aldarate_Metabolism",	"Urea_cycle;_Arginine_and_Proline_Metabolism",	"Glutamate_Metabolism",	"Pyrimidine_Metabolism_Uracil_containing",	"Pyrimidine_Metabolism_Cytidine_containing",	"Fatty_Acid_Dihydroxy",	"Tyrosine_Metabolism",	"Mevalonate_Metabolism",	"Ketone_Bodies",	"Fatty_Acid_Monohydroxy",	"Tryptophan_Metabolism",	"Benzoate_Metabolism",	"Guanidino_and_Acetamido_Metabolism",	"Lysine_Metabolism",	"Pyrimidine_Metabolism_Thymine_containing",	"Purine_Metabolism_Guanine_containing",	"Sterol",	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Short_Chain)",	"Purine_Metabolism_Adenine_containing",	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Dicarboxylate)",	"Alanine_and_Aspartate_Metabolism",	"Purine_Metabolism_(Hypo)Xanthine_Inosine_containing",	"Glycine_Serine_and_Threonine_Metabolism",	"Tocopherol_Metabolism",	"Pentose_Metabolism",	"Hemoglobin_and_Porphyrin_Metabolism",	"Carnitine_Metabolism",	"Inositol_Metabolism",	"Phospholipid_Metabolism",	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Medium_Chain)",	"Fatty_Acid_Metabolism_(Acyl_Carnitine_Monounsaturated)",	"Corticosteroids",	"Creatine_Metabolism",	"Dipeptide",	"Secondary_Bile_Acid_Metabolism",	"Aminosugar_Metabolism",	"Fructose_Mannose_and_Galactose_Metabolism",	"Galactosyl_Glycerolipids",	"Gamma-glutamyl_Amino_Acid",	"Partially_Characterized_Molecules",	"Glycerolipid_Metabolism",	"Phenylalanine_Metabolism",	"Lactoyl_Amino_Acid",	"Modified_Peptides",	"Pyrimidine_Metabolism_Orotate_containing",	"Sphingomyelins",	"Pantothenate_and_CoA_Metabolism",	"Acetylated_Peptides",	"Oxidative_Phosphorylation",	"Fatty_Acid_Metabolism_(also_BCAA_Metabolism)",	"Vitamin_B6_Metabolism",	"Vitamin_A_Metabolism",	"Drug_-_Topical_Agents",	"Disaccharides_and_Oligosaccharides"]
for subpath in subpath_name:
    l = ["sid"]
    with open ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/Sub-Pathway/Subpathway_Data.txt", 'r') as subpath_data:
        line = subpath_data.readline ()
        for line in subpath_data:
            line_list = line.split ("\t")
            if (str(line_list [0]) == str(subpath)):
                l.append (str (line_list [2]))
    print (l)
    df = pd.read_csv ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/A_Beta/5_Data_Full_Imputed_Analysis_A_beta.txt", delimiter="\t")
    df_2 = df[l]
    df_2.to_csv ("/Volumes/ATUL_6TB/Work/Projects/CSF_Metabolomics/Analyses_2/Sub-Pathway/Data_Sub_Pathway/" + str (subpath) + ".txt", sep="\t", index=False)
